#!/bin/bash
SOURCEPATH="/home/$USER/.minecraft/forge/moddingEnvironments"
cd $SOURCEPATH
find MFS102/src -not -path *.git* -not -type l -not -type d -delete
cp -rPnu MFS94/src/main MFS102/src/
FILES=$(find MFS102/src -not -path *.git* -not -type l -not -type d)

for FILE in ${FILES[*]}; do
#Global changes
sed -i '/INS1002/d' $FILE
sed -i '/DEL1002START/,/DEL1002END/d' $FILE

#File-specifc changes

done
